### ISSUE TITLE
Candidates gathering

### ISSUE THREAD

**Issue by paniksystem** [paullouisageneau/libjuice#10]
I am unable to generate candidates that firefox can connect to using libjuice.
Candidates gathered using webrtc standard implementation (libnice):
```
candidate:390988917 1 udp 2122260223 192.168.122.127 52942 typ host generation 0 ufrag hCZ1 network-id 1
candidate:1506670725 1 tcp 1518280447 192.168.122.127 62560 typ host tcptype passive generation 0 ufrag hCZ1 network-id 1
candidate:2122599348 1 udp 1686052607 [PUBLIC IP] 52942 typ srflx raddr 192.168.122.127 rport 52942 generation 0 ufrag hCZ1 network-id 1
```

Candidates gathered using libjuice:
```
a=candidate:1 1 UDP 2122317823 192.168.122.127 58201 typ host
a=candidate:2 1 UDP 1686110207 [PUBLIC IP] 58201 typ srflx
```

**Comment by paniksystem** [comment]
I should point that chrome can successfuly connect with both candidates (libnice and libjuice generated ones) but i also would like to connect with firefox :D

**Comment by paniksystem** [comment]
I found the problem, firefox refuse srflx candidates without
`raddr 0.0.0.0 rport 0`
This is more of a firefox bug?, but it should be considered.
Feel free to close this issue

**Comment by paullouisageneau** [comment]
Thank you for testing every combination :D
It's no big deal, I added `raddr 0.0.0.0 rport 0` to generated candidates: https://github.com/paullouisageneau/libjuice/commit/d29c76021abc4330c007f9b1d5bde4a1883132e2

**Comment by paniksystem** [comment]
Thank you for doing the real hard work :D
