### ISSUE TITLE
UDP Port Range

### ISSUE THREAD

**Issue by paniksystem** [paullouisageneau/libjuice#12]
Quick question: would it be possible to specify a port range when making the first connection to the STUN server ?

**Comment by paullouisageneau** [comment]
Yes, this is not hard to implement and is currently not supported compared to libnice. However, the port range would apply to STUN servers and P2P connections, since the same port must be used for both.

**Comment by paullouisageneau** [comment]
It's now available in libjuice and libdatachannel!

**Comment by paniksystem** [comment]
wow, nice! (i mean juicy!) thank you :D

**Comment by paniksystem** [comment]
just a quick info, while reviewing the pull request, i noticed that 
`uint16_t udp_get_port(socket_t sock);`
is defined in udp.h but seems to be declared juice_udp_get_port in udp.c

**Comment by paullouisageneau** [comment]
Thanks, I'll fix the header, it's indeed incorrect!
