### ISSUE TITLE
poll failed, errno=22

### ISSUE THREAD

**Issue by tugrul** [paullouisageneau/libjuice#127]
Hi, 

I'm trying to run violet server on (x86) and (Raspberry PI armv71) Debian 10 but it is facing following error on both platforms.

```
$ ./violet --credentials=test:123
2021-09-22 22:56:23 INFO    server.c:214: Created server on port 3478
2021-09-22 22:56:23 FATAL   server.c:387: poll failed, errno=22
```

**Comment by paullouisageneau** [comment]
Thanks for reporting, I can reproduce with an older kernel (5.10.60). It comes from a limitation of the `poll` function which only supports 1024 entries, whereas the default of 1024 allocations results in 1025 entries.

I'll push a fix, in the meantime you can make it work by reducing the maximum number of allocations:
```
$ ./violet --credentials=test:123 --max=1000
```
