### ISSUE TITLE
Visual Studio 2019

### ISSUE THREAD

**Issue by paniksystem** [paullouisageneau/libjuice#14]
When using visual studio 2017, everything is fine, working like a charm. But i recently tried to build on a machine who is running visual studio 2019, and i get an error trying to send stun messages:

`STUN message send failed, errno=10049`

Do you have any idea how to fix this?

**Comment by paullouisageneau** [comment]
Is it for every STUN message or only some of them ?

According to [Windows documentation](https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2), Winsock error 10049 on sendto means `The remote address is not a valid address, for example, ADDR_ANY. `.

My guess is the sockaddr structure needs to be zeroed now for some reason. Could you please try adding `memset(sin6, 0, sizeof(*sin6));` after this line in libjuice: https://github.com/paullouisageneau/libjuice/blob/master/src/addr.c#L133

**Comment by paullouisageneau** [comment]
Please re-open the issue if the fix didn't solve the problem for you.

**Comment by paniksystem** [comment]
I'm so sorry i did not reply sooner, i switched back to 2017 in a hurry, i will try to test it and reopen if needed, thank you!
