### ISSUE TITLE
How can I support windows XP, I want to use this project under XP

### ISSUE THREAD

**Issue by fengshangren** [paullouisageneau/libjuice#168]
How can I support windows XP, I want to use this project under XP

**Comment by paullouisageneau** [comment]
The library requires at least Microsoft Windows 7. To make in compatible with older legacy versions like Windows XP, you would need to implement workarounds for missing functions in the system API, for instance `WSAPoll` and `BCryptGenRandom`.

To be honest, Windows XP has been unsupported for more than 8 years, even the exceptional support for Windows Embedded ended a few years ago, and most third-party software dropped support nowadays. It shouldn't be used anymore.
