### ISSUE TITLE
How does the stun/trun server get the candidates of the peer

### ISSUE THREAD

**Issue by fengshangren** [paullouisageneau/libjuice#169]
How does the stun/trun server get the candidates of the peer

**Comment by paullouisageneau** [comment]
What do you mean?

**Comment by fengshangren** [comment]
For example, how to exchange the sdp between the A side and the B side? It seems that libjuice itself can't do it.

**Comment by paullouisageneau** [comment]
The STUN/TURN are used by the ICE protocol to gather local candidates, then it's up to the user application to transmit the description and candidates to the other side. This is typically done with a signaling server like in the case of SIP or WebRTC.

**Comment by fengshangren** [comment]
Can you talk about the principle of libjuice's TURN? How does he forward it?

**Comment by paullouisageneau** [comment]
TURN servers are not specific to libjuice. They allow to allocate a UDP port an the server to relay the UDP traffic if the network is blocked on the client, typically by an endpoint-dependent (aka symmetric) NAT that can't be traversed.

**Comment by paullouisageneau** [comment]
I'm closing this as it's not an issue.
