### ISSUE TITLE
How to force peer connect using relay

### ISSUE THREAD

**Issue by apinprastya** [paullouisageneau/libjuice#171]
Is there any way to force peer connect using turn relay? I hack it by checking the candidates only process if it contain `typ relay`. Is that correct path to do it?

**Comment by paullouisageneau** [comment]
At the moment there is no setting to force TURN relaying. You may indeed filter candidates and pass only relay ones.

**Comment by apinprastya** [comment]
ok thanks for the answer, will close it.
