### ISSUE TITLE
Ask about libnice related issues, I use the agent created by nice_agent_new_reliable, but the reliable transmission efficiency of UDP inside is very low. How can I improve it? I really need an efficient and reliable UDP transport

### ISSUE THREAD

**Issue by fengshangren** [paullouisageneau/libjuice#172]
Ask about libnice related issues, I use the agent created by nice_agent_new_reliable, but the reliable transmission efficiency of UDP inside is very low. How can I improve it? I really need an efficient and reliable UDP transport

**Comment by paullouisageneau** [comment]
This is not related to libjuice and should be reported to the [libnice repository](https://gitlab.freedesktop.org/libnice/libnice/-/issues).
