### ISSUE TITLE
Bug, after setting relay, when calling juice_send, it will block. It is suspected to be deadlock

### ISSUE THREAD

**Issue by fengshangren** [paullouisageneau/libjuice#179]
Bug, after setting relay, when calling juice_send, it will block. It is suspected to be deadlock. After the client interacts with the relay a few times, it will block and will not return when it executes juice_send again.

**Comment by fengshangren** [comment]
I have been testing for a long time. As long as I don't use relays and only use p2p, the transfer is normal. But after setting relay, juice_send will block after being sent multiple times and will not return. what is the reason?

**Comment by paullouisageneau** [comment]
Please provide code that reproduces the issue.

Also, you should check that you are not blocking one of libjuice's callback while calling `juice_send` in another thread. This may lead to such behaviour.

**Comment by fengshangren** [comment]
int agent_send(juice_agent_t *agent, const char *data, size_t size, int ds) {
	// Try not to lock in the send path
	agent_stun_entry_t *selected_entry = atomic_load(&agent->selected_entry);
	if (!selected_entry) {
		JLOG_ERROR("Send called before ICE is connected");
		return -1;
	}

	atomic_store(&selected_entry->armed, false); // so keepalive will be rescheduled

	if (selected_entry->relay_entry) {
		// The datagram should be sent through the relay, use a channel to minimize overhead
		**conn_lock(agent)**; // We have to lock
		int ret = agent_channel_send(agent, selected_entry->relay_entry, &selected_entry->record,
		                             data, size, ds);
		conn_unlock(agent);
		return ret;
	}

	return agent_direct_send(agent, &selected_entry->record, data, size, ds);
}



When debugging, he will be blocked here （conn_lock(agent)）

**Comment by paullouisageneau** [comment]
This is not useful, please provide a minimal version of the code you use to call the library and trigger the issue.

**Comment by paullouisageneau** [comment]
@fengshangren Is it solved?
