### ISSUE TITLE
Does juice_add_remote_candidate have to be called p2p in on_candidate or on_gathering_done callback to be effective?

### ISSUE THREAD

**Issue by fengshangren** [paullouisageneau/libjuice#181]
I have been unsuccessful in p2p today. I have tested many times and found that juice_add_remote_candidate must be called in the on_candidate or on_gathering_done callback for p2p to succeed. Is this true?

**Comment by paullouisageneau** [comment]
Please prefer discussions to ask questions rather than issues in the future.

> I have tested many times and found that juice_add_remote_candidate must be called in the on_candidate or on_gathering_done callback for p2p to succeed. Is this true?

`juice_add_remote_candidate` must be called when receiving a candidate from the remote side: when one side obtains a candidate in `on_candidate`, it sends it to the other side, which receives it and pass it to `juice_add_remote_candidate`.

However, if you choose to send the descriptions with candidates inside by sending the local description in `on_gathering_done` rather than immediately, `juice_add_remote_candidate` should not be used and `on_candidate` should be ignored (see the `notrickle` test).

**Comment by paullouisageneau** [comment]
Please prefer discussions to ask questions rather than opening issues in the future.

> I have tested many times and found that juice_add_remote_candidate must be called in the on_candidate or on_gathering_done callback for p2p to succeed. Is this true?

`juice_add_remote_candidate` must be called when receiving a candidate from the remote side: when one side obtains a candidate in `on_candidate`, it sends it to the other side, which receives it and pass it to `juice_add_remote_candidate`.

However, if you choose to send the descriptions with candidates inside by sending the local description in `on_gathering_done` rather than immediately, `juice_add_remote_candidate` should not be used and `on_candidate` should be ignored (see the `notrickle` test).

**Comment by fengshangren** [comment]
#include <iostream>

/**
 * Copyright (c) 2020 Paul-Louis Ageneau
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

#include "juice/juice.h"

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
using namespace std;
#ifdef _WIN32
#include <windows.h>
static void sleep(unsigned int secs) { Sleep(secs * 1000); }
#else
#include <unistd.h> // for sleep
#endif

#define BUFFER_SIZE 4096

static juice_agent_t* agent;
static void on_state_changed(juice_agent_t* agent, juice_state_t state, void* user_ptr);
static void on_gathering_done(juice_agent_t* agent, void* user_ptr);
static void on_recv(juice_agent_t* agent, const char* data, size_t size, void* user_ptr);


int test_notrickle() {
	juice_set_log_level(JUICE_LOG_LEVEL_NONE);

	// Agent 1: Create agent
	juice_config_t config1;
	memset(&config1, 0, sizeof(config1));
	config1.stun_server_host = "stun.qq.com";
	config1.stun_server_port = 3478;
	config1.cb_state_changed = on_state_changed;
	config1.cb_gathering_done = on_gathering_done;
	config1.cb_recv = on_recv;
	config1.user_ptr = NULL;

	agent = juice_create(&config1);

	juice_gather_candidates(agent);

	sleep(4);

	char localsdp[JUICE_MAX_SDP_STRING_LEN];
	juice_get_local_description(agent, localsdp, JUICE_MAX_SDP_STRING_LEN);
	cout << "\nLocalSdp:\n"<<localsdp << endl;


	cout << "RemoteSdp: " << endl;
	char remotesdp[4096] = {}, remotesdpline[256]={};
	while (cin.getline(remotesdpline, sizeof(remotesdpline)))
	{

		strcat(remotesdp, remotesdpline);
		strcat(remotesdp, "\r\n");
		if (strcmp(remotesdpline, "a=end-of-candidates") == 0)
		{
			strcat(remotesdp, "a=ice-options:ice2");
			break;

		}
	}

	char str[4096];
	cin >> str;
	juice_set_remote_description(agent, remotesdp);
	cout << "\n" << endl;
	sleep(2);
	// -- Connection should be finished --

	// Check states
	juice_state_t state1 = juice_get_state(agent);
	bool success = (state1 == JUICE_STATE_COMPLETED);

	// Retrieve candidates
	char local[JUICE_MAX_CANDIDATE_SDP_STRING_LEN];
	char remote[JUICE_MAX_CANDIDATE_SDP_STRING_LEN];
	if (success &=
		(juice_get_selected_candidates(agent, local, JUICE_MAX_CANDIDATE_SDP_STRING_LEN, remote,
			JUICE_MAX_CANDIDATE_SDP_STRING_LEN) == 0)) {
		printf("Local candidate  1: %s\n", local);
		printf("Remote candidate 1: %s\n", remote);
	}


	// Retrieve addresses
	char localAddr[JUICE_MAX_ADDRESS_STRING_LEN];
	char remoteAddr[JUICE_MAX_ADDRESS_STRING_LEN];
	if (success &= (juice_get_selected_addresses(agent, localAddr, JUICE_MAX_ADDRESS_STRING_LEN,
		remoteAddr, JUICE_MAX_ADDRESS_STRING_LEN) == 0)) {
		printf("Local address  1: %s\n", localAddr);
		printf("Remote address 1: %s\n", remoteAddr);
		if ((!strstr(local, "typ host") && !strstr(local, "typ prflx")) ||
			(!strstr(remote, "typ host") && !strstr(remote, "typ prflx")))
			success = false; // local connection should be possible
	}


	// Agent 1: destroy
	juice_destroy(agent);

	// Sleep so we can check destruction went well
	sleep(2);


	if (success) {
		printf("Success\n");
		return 0;
	}
	else {
		printf("Failure\n");
		return -1;
	}
}

// Agent 1: on state changed
static void on_state_changed(juice_agent_t* agent, juice_state_t state, void* user_ptr) {
	printf("State 1: %s\n", juice_state_to_string(state));

	if (state == JUICE_STATE_CONNECTED) {
		// Agent 1: on connected, send a message
		const char* message = "Hello from 1";
		juice_send(agent, message, strlen(message));
	}
}


// Agent 1: on local candidates gathering done
static void on_gathering_done(juice_agent_t* agent, void* user_ptr) {
	printf("Gathering done 1\n");


}


// Agent 1: on message received
static void on_recv(juice_agent_t* agent, const char* data, size_t size, void* user_ptr) {
	char buffer[BUFFER_SIZE];
	if (size > BUFFER_SIZE - 1)
		size = BUFFER_SIZE - 1;
	memcpy(buffer, data, size);
	buffer[size] = '\0';
	printf("Received 1: %s\n", buffer);
}

int main()
{
	test_notrickle();
	Sleep(99999999);
}

**Comment by fengshangren** [comment]
#include <iostream>

/**
 * Copyright (c) 2020 Paul-Louis Ageneau
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

#include "juice/juice.h"

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
using namespace std;
#ifdef _WIN32
#include <windows.h>
static void sleep(unsigned int secs) { Sleep(secs * 1000); }
#else
#include <unistd.h> // for sleep
#endif

#define BUFFER_SIZE 4096

static juice_agent_t* agent;
static void on_state_changed(juice_agent_t* agent, juice_state_t state, void* user_ptr);
static void on_gathering_done(juice_agent_t* agent, void* user_ptr);
static void on_recv(juice_agent_t* agent, const char* data, size_t size, void* user_ptr);


int test_notrickle() {
	juice_set_log_level(JUICE_LOG_LEVEL_NONE);

	// Agent 1: Create agent
	juice_config_t config1;
	memset(&config1, 0, sizeof(config1));
	config1.stun_server_host = "stun.qq.com";
	config1.stun_server_port = 3478;
	config1.cb_state_changed = on_state_changed;
	config1.cb_gathering_done = on_gathering_done;
	config1.cb_recv = on_recv;
	config1.user_ptr = NULL;

	agent = juice_create(&config1);

	juice_gather_candidates(agent);

	sleep(4);

	char localsdp[JUICE_MAX_SDP_STRING_LEN];
	juice_get_local_description(agent, localsdp, JUICE_MAX_SDP_STRING_LEN);
	cout << "\nLocalSdp:\n"<<localsdp << endl;


	cout << "RemoteSdp: " << endl;
	char remotesdp[4096] = {}, remotesdpline[256]={};
	while (cin.getline(remotesdpline, sizeof(remotesdpline)))
	{

		strcat(remotesdp, remotesdpline);
		strcat(remotesdp, "\r\n");
		if (strcmp(remotesdpline, "a=end-of-candidates") == 0)
		{
			strcat(remotesdp, "a=ice-options:ice2");
			break;

		}
	}

	char str[4096];
	cin >> str;
	juice_set_remote_description(agent, remotesdp);
	cout << "\n" << endl;
	sleep(3);



	// -- Connection should be finished --

	// Check states
	juice_state_t state1 = juice_get_state(agent);
	bool success = (state1 == JUICE_STATE_COMPLETED);

	// Retrieve candidates
	char local[JUICE_MAX_CANDIDATE_SDP_STRING_LEN];
	char remote[JUICE_MAX_CANDIDATE_SDP_STRING_LEN];
	if (success &=
		(juice_get_selected_candidates(agent, local, JUICE_MAX_CANDIDATE_SDP_STRING_LEN, remote,
			JUICE_MAX_CANDIDATE_SDP_STRING_LEN) == 0)) {
		printf("Local candidate  1: %s\n", local);
		printf("Remote candidate 1: %s\n", remote);
	}


	// Retrieve addresses
	char localAddr[JUICE_MAX_ADDRESS_STRING_LEN];
	char remoteAddr[JUICE_MAX_ADDRESS_STRING_LEN];
	if (success &= (juice_get_selected_addresses(agent, localAddr, JUICE_MAX_ADDRESS_STRING_LEN,
		remoteAddr, JUICE_MAX_ADDRESS_STRING_LEN) == 0)) {
		printf("Local address  1: %s\n", localAddr);
		printf("Remote address 1: %s\n", remoteAddr);
		if ((!strstr(local, "typ host") && !strstr(local, "typ prflx")) ||
			(!strstr(remote, "typ host") && !strstr(remote, "typ prflx")))
			success = false; // local connection should be possible
	}


	// Agent 1: destroy
	juice_destroy(agent);

	// Sleep so we can check destruction went well
	sleep(2);


	if (success) {
		printf("Success\n");
		return 0;
	}
	else {
		printf("Failure\n");
		return -1;
	}
}

// Agent 1: on state changed
static void on_state_changed(juice_agent_t* agent, juice_state_t state, void* user_ptr) {
	printf("State 1: %s\n", juice_state_to_string(state));

	if (state == JUICE_STATE_CONNECTED) {
		// Agent 1: on connected, send a message
		const char* message = "Hello from 1";
		juice_send(agent, message, strlen(message));
	}
}


// Agent 1: on local candidates gathering done
static void on_gathering_done(juice_agent_t* agent, void* user_ptr) {
	printf("Gathering done 1\n");


}


// Agent 1: on message received
static void on_recv(juice_agent_t* agent, const char* data, size_t size, void* user_ptr) {
	char buffer[BUFFER_SIZE];
	if (size > BUFFER_SIZE - 1)
		size = BUFFER_SIZE - 1;
	memcpy(buffer, data, size);
	buffer[size] = '\0';
	printf("Received 1: %s\n", buffer);
}

int main()
{
	test_notrickle();
	Sleep(99999999);
}

**Comment by fengshangren** [comment]
I changed it to a remote P2P test example based on notrickle.c. This example can be directly connected to a local area network or a computer with a public network IP, but both ends are in a NAT environment, and the P2P always fails. You can try it

**Comment by paullouisageneau** [comment]
What do you mean by P2P always fail? This example will fail if connecting through NATs as you left the check that the connection is local:
```
if ((!strstr(local, "typ host") && !strstr(local, "typ prflx")) ||
			(!strstr(remote, "typ host") && !strstr(remote, "typ prflx")))
			success = false; // local connection should be possible
```

**Comment by fengshangren** [comment]
The code you said has nothing to do with it. You can comment out the code you mentioned and test again, but the P2P direct connection will always fail, that is, the P2P direct connection will always fail and will not succeed. Why don't you try it?

**Comment by fengshangren** [comment]
#include <iostream>

/**
 * Copyright (c) 2020 Paul-Louis Ageneau
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

#include "juice/juice.h"

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
using namespace std;
#ifdef _WIN32
#include <windows.h>
static void sleep(unsigned int secs) { Sleep(secs * 1000); }
#else
#include <unistd.h> // for sleep
#endif

#define BUFFER_SIZE 4096

static juice_agent_t* agent;
static void on_state_changed(juice_agent_t* agent, juice_state_t state, void* user_ptr);
static void on_gathering_done(juice_agent_t* agent, void* user_ptr);
static void on_recv(juice_agent_t* agent, const char* data, size_t size, void* user_ptr);


int test_notrickle() {
	juice_set_log_level(JUICE_LOG_LEVEL_NONE);

	// Agent 1: Create agent
	juice_config_t config1;
	memset(&config1, 0, sizeof(config1));
	config1.stun_server_host = "stun.qq.com";
	config1.stun_server_port = 3478;
	config1.cb_state_changed = on_state_changed;
	config1.cb_gathering_done = on_gathering_done;
	config1.cb_recv = on_recv;
	config1.user_ptr = NULL;

	agent = juice_create(&config1);

	juice_gather_candidates(agent);

	sleep(4);

	char localsdp[JUICE_MAX_SDP_STRING_LEN];
	juice_get_local_description(agent, localsdp, JUICE_MAX_SDP_STRING_LEN);
	cout << "\nLocalSdp:\n"<<localsdp << endl;


	cout << "RemoteSdp: " << endl;
	char remotesdp[4096] = {}, remotesdpline[256]={};
	while (cin.getline(remotesdpline, sizeof(remotesdpline)))
	{

		strcat(remotesdp, remotesdpline);
		strcat(remotesdp, "\r\n");
		if (strcmp(remotesdpline, "a=end-of-candidates") == 0)
		{
			strcat(remotesdp, "a=ice-options:ice2");
			break;

		}
	}

	char str[4096];
	cin >> str;
	juice_set_remote_description(agent, remotesdp);
	cout << "\n" << endl;
	sleep(4);
	// -- Connection should be finished --

	// Check states
	juice_state_t state1 = juice_get_state(agent);
	bool success = (state1 == JUICE_STATE_CONNECTED || state1 == JUICE_STATE_COMPLETED);

	// Retrieve candidates
	char local[JUICE_MAX_CANDIDATE_SDP_STRING_LEN];
	char remote[JUICE_MAX_CANDIDATE_SDP_STRING_LEN];
	if (success &=
		(juice_get_selected_candidates(agent, local, JUICE_MAX_CANDIDATE_SDP_STRING_LEN, remote,
			JUICE_MAX_CANDIDATE_SDP_STRING_LEN) == 0)) {
		printf("Local candidate  1: %s\n", local);
		printf("Remote candidate 1: %s\n", remote);
	}

	// Agent 1: destroy
	juice_destroy(agent);

	// Sleep so we can check destruction went well
	sleep(2);


	if (success) {
		printf("Success\n");
		return 0;
	}
	else {
		printf("Failure\n");
		return -1;
	}
}

// Agent 1: on state changed
static void on_state_changed(juice_agent_t* agent, juice_state_t state, void* user_ptr) {
	printf("State 1: %s\n", juice_state_to_string(state));

	if (state == JUICE_STATE_CONNECTED) {
		// Agent 1: on connected, send a message
		const char* message = "Hello from 1";
		juice_send(agent, message, strlen(message));
	}
}


// Agent 1: on local candidates gathering done
static void on_gathering_done(juice_agent_t* agent, void* user_ptr) {
	printf("Gathering done 1\n");


}


// Agent 1: on message received
static void on_recv(juice_agent_t* agent, const char* data, size_t size, void* user_ptr) {
	char buffer[BUFFER_SIZE];
	if (size > BUFFER_SIZE - 1)
		size = BUFFER_SIZE - 1;
	memcpy(buffer, data, size);
	buffer[size] = '\0';
	printf("\nReceived 1: %s\n", buffer);
}

int main()
{
	test_notrickle();
	Sleep(99999999);
}

**Comment by fengshangren** [comment]
The P2P failure has nothing to do with the code you mentioned. You can comment out the code you mentioned and test it again. I mean that the code in your notrickle example is used in a remote NAT environment, and the P2P direct connection will never be possible success. Why don't you try it?

**Comment by fengshangren** [comment]
You want to test on two computers with a NAT traversable environment, but this example will never succeed in a direct P2P connection

**Comment by paullouisageneau** [comment]
> You want to test on two computers with a NAT traversable environment, but this example will never succeed in a direct P2P connection

I spend time doing so, and it succeeds.

Output for peer 1:
```
State 1: gathering
State 1: connecting
Gathering done 1

LocalSdp:
a=ice-ufrag:Aic6
a=ice-pwd:hwn5CxuyHuXG3AoHThyiO9
a=candidate:1 1 UDP 2122317823 192.168.139.114 34709 typ host
a=candidate:2 1 UDP 1686109951 77.63.X.X 36413 typ srflx raddr 0.0.0.0 rport 0
a=end-of-candidates
a=ice-options:ice2


RemoteSdp: 
a=ice-ufrag:P9rE
a=ice-pwd:Iaoo/UE52DodM+fXTpuGYy
a=candidate:3 1 UDP 2130705919 2a02:X:X:X:X:X:X:X 53396 typ host
a=candidate:1 1 UDP 2122317823 10.9.0.101 53396 typ host
a=candidate:3 1 UDP 1686108927 77.249.X.X 53396 typ srflx raddr 0.0.0.0 rport 0
a=end-of-candidates
a=ice-options:ice2



State 1: connected
Received 1: Hello from 1
State 1: completed
Local candidate  1: a=candidate:2 1 UDP 1686109951 77.63.X.X 36413 typ srflx raddr 0.0.0.0 rport 0
Remote candidate 1: a=candidate:6 1 UDP 1686108927 77.249.X.X 53396 typ srflx raddr 0.0.0.0 rport 0
Success

Output for peer 2:
```
State 1: gathering
State 1: connecting
Gathering done 1

LocalSdp:
a=ice-ufrag:P9rE
a=ice-pwd:Iaoo/UE52DodM+fXTpuGYy
a=candidate:3 1 UDP 2130705919 2a02:X:X:X:X:X:X:X 53396 typ host
a=candidate:1 1 UDP 2122317823 10.9.0.101 53396 typ host
a=candidate:3 1 UDP 1686108927 77.249.X.X 53396 typ srflx raddr 0.0.0.0 rport 0
a=end-of-candidates
a=ice-options:ice2


RemoteSdp: 
a=ice-ufrag:Aic6
a=ice-pwd:hwn5CxuyHuXG3AoHThyiO9
a=candidate:1 1 UDP 2122317823 192.168.139.114 34709 typ host
a=candidate:2 1 UDP 1686109951 77.63.X.X 36413 typ srflx raddr 0.0.0.0 rport 0
a=end-of-candidates
a=ice-options:ice2



Received 1: Hello from 1
State 1: connected
State 1: completed
Local candidate  1: a=candidate:6 1 UDP 1686108927 77.249.X.X 53396 typ srflx raddr 0.0.0.0 rport 0
Remote candidate 1: a=candidate:2 1 UDP 1686109951 77.63.X.X 36413 typ srflx raddr 0.0.0.0 rport 0
Success
```

You should fix the extremely short `sleep(4)` with `sleep(30)` in your code. As it is, the first peer to get the remote description will wait for only 4 seconds, then destroy the agent and print success or failure. This obviously makes manual testing very difficult.

Then, your code to read the remote SDP is bad, it mixes C and C++, doesn't check bounds and will break if gathering is not finished or if you forget to press enter at the end. You should rewrite it correctly, for instance:
```
cout << "RemoteSdp: " << endl;
string remotesdp, remotesdpline;
while (getline(cin, remotesdpline))
{
	if (remotesdpline.empty())
		break;

	remotesdp += remotesdpline + "\r\n";
}

cout << remotesdp <<endl;
juice_set_remote_description(agent, remotesdp.c_str());
cout << "OK" << endl;
sleep(30);
```

Finally, please develop a proper signaling channel to automatically forward descriptions and candidates between agents rather than relying on clumsy manual copy-pasting between machines. It's unreliable since you might not be able to do so manually before the first peer times out.

**Comment by paullouisageneau** [comment]
> You want to test on two computers with a NAT traversable environment, but this example will never succeed in a direct P2P connection

I spend time doing so, and it succeeds.

Output for peer 1:
```
State 1: gathering
State 1: connecting
Gathering done 1

LocalSdp:
a=ice-ufrag:Aic6
a=ice-pwd:hwn5CxuyHuXG3AoHThyiO9
a=candidate:1 1 UDP 2122317823 192.168.139.114 34709 typ host
a=candidate:2 1 UDP 1686109951 77.63.X.X 36413 typ srflx raddr 0.0.0.0 rport 0
a=end-of-candidates
a=ice-options:ice2


RemoteSdp: 
a=ice-ufrag:P9rE
a=ice-pwd:Iaoo/UE52DodM+fXTpuGYy
a=candidate:3 1 UDP 2130705919 2a02:X:X:X:X:X:X:X 53396 typ host
a=candidate:1 1 UDP 2122317823 10.9.0.101 53396 typ host
a=candidate:3 1 UDP 1686108927 77.249.X.X 53396 typ srflx raddr 0.0.0.0 rport 0
a=end-of-candidates
a=ice-options:ice2



State 1: connected
Received 1: Hello from 1
State 1: completed
Local candidate  1: a=candidate:2 1 UDP 1686109951 77.63.X.X 36413 typ srflx raddr 0.0.0.0 rport 0
Remote candidate 1: a=candidate:6 1 UDP 1686108927 77.249.X.X 53396 typ srflx raddr 0.0.0.0 rport 0
Success
```

Output for peer 2:
```
State 1: gathering
State 1: connecting
Gathering done 1

LocalSdp:
a=ice-ufrag:P9rE
a=ice-pwd:Iaoo/UE52DodM+fXTpuGYy
a=candidate:3 1 UDP 2130705919 2a02:X:X:X:X:X:X:X 53396 typ host
a=candidate:1 1 UDP 2122317823 10.9.0.101 53396 typ host
a=candidate:3 1 UDP 1686108927 77.249.X.X 53396 typ srflx raddr 0.0.0.0 rport 0
a=end-of-candidates
a=ice-options:ice2


RemoteSdp: 
a=ice-ufrag:Aic6
a=ice-pwd:hwn5CxuyHuXG3AoHThyiO9
a=candidate:1 1 UDP 2122317823 192.168.139.114 34709 typ host
a=candidate:2 1 UDP 1686109951 77.63.X.X 36413 typ srflx raddr 0.0.0.0 rport 0
a=end-of-candidates
a=ice-options:ice2



Received 1: Hello from 1
State 1: connected
State 1: completed
Local candidate  1: a=candidate:6 1 UDP 1686108927 77.249.X.X 53396 typ srflx raddr 0.0.0.0 rport 0
Remote candidate 1: a=candidate:2 1 UDP 1686109951 77.63.X.X 36413 typ srflx raddr 0.0.0.0 rport 0
Success
```

You should fix the extremely short `sleep(4)` with `sleep(30)` in your code. As it is, the first peer to get the remote description will wait for only 4 seconds, then destroy the agent and print success or failure. This obviously makes manual testing very difficult.

Then, your code to read the remote SDP is bad, it mixes C and C++, doesn't check bounds and will break if gathering is not finished or if you forget to press enter at the end. You should rewrite it correctly, for instance:
```
cout << "RemoteSdp: " << endl;
string remotesdp, remotesdpline;
while (getline(cin, remotesdpline))
{
	if (remotesdpline.empty())
		break;

	remotesdp += remotesdpline + "\r\n";
}

cout << remotesdp <<endl;
juice_set_remote_description(agent, remotesdp.c_str());
cout << "OK" << endl;
sleep(30);
```

Finally, please develop a proper signaling channel to automatically forward descriptions and candidates between agents rather than relying on clumsy manual copy-pasting between machines. It's unreliable since you might not be able to do so manually before the first peer times out.

**Comment by paullouisageneau** [comment]
I'm closing this as it is not an issue with libjuice.

**Comment by paullouisageneau** [comment]
I'm closing this as it doesn't look like an issue with libjuice.
