### ISSUE TITLE
Re-licensing under MPL 2.0

### ISSUE THREAD

**Issue by paullouisageneau** [paullouisageneau/libjuice#183]
After different discussions, there seems to be a common blocking point with the difficulty to bundle the library into closed-source apps due to the LGPL license, even the impossibility to do so for apps in Apple's App store. Therefore, I'd like to re-license libjuice under [MPL 2.0](https://www.mozilla.org/en-US/MPL/2.0/).

The MPL 2.0 is also a weak copyleft license like the LGPL and is compatible with the GPL. Basically, modifications must still be redistributed under the same license, but the license applies on file level which allows combining the code with code under any other license. In particular, it would allow static linking the library with closed-source applications without restrictions (see more information in the [MPL 2.0 FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/)). It should not change anything for current libjuice users.

As a side node, libnice, another popular ICE implementation, is licensed under LGPL-2.1 or MPL-1.0. MPL-2.0 is compatible with secondary licenses like LGPL-2.1 by default and doesn't require explicit dual licensing.

@VollmondT @0x34d @csteuer You have made contributions to the library's code, for which I thank you again. Could you please confirm here whether you agree with the re-licensing under MPL 2.0?

**Comment by 0x34d** [comment]
Alright.

**Comment by csteuer** [comment]
Agreed

**Comment by VollmondT** [comment]
Agreed

**Comment by paullouisageneau** [comment]
Thank you for your answers!

**Comment by paullouisageneau** [comment]
I glad to announce that libjuice is now under MPL 2.0!
