### ISSUE TITLE
Can libjuice support candidates re-gathering?

### ISSUE THREAD

**Issue by yasincy** [paullouisageneau/libjuice#188]
I'm trying to use libjuice on phone. When i turn off Wi-Fi and go to cellular network, cellular candidates are not gathered. I try to force re-gather with calling "juice_gather_candidates" and get the error "Candidates gathering already started".

**Comment by paullouisageneau** [comment]
This corresponds to ICE restart, which is currently not supported. The issue is https://github.com/paullouisageneau/libjuice/issues/130.

For now, you need to recreate an agent to attempt a reconnection when it disconnects.

**Comment by paullouisageneau** [comment]
I'm closing this as duplicate.
