### ISSUE TITLE
WSAIoctl with SIO_GET_INTERFACE failed, errno=10022

### ISSUE THREAD

**Issue by paniksystem** [paullouisageneau/libjuice#2]
On Windows 10, WSAIoctl fails when using a socket AF_INET6.

**Comment by paullouisageneau** [comment]
It seems `SIO_GET_INTERFACE_LIST` is legacy, I replaced it with `SIO_ADDRESS_LIST_QUERY` which is garanteed to support IPv6 properly: https://github.com/paullouisageneau/libjuice/commit/567b9f150db8b22679b1f4ff60d3bed4d0075fa3
 It works fine on my side, could you try on yours?

**Comment by paniksystem** [comment]
"Gathered host candidate" Seems to be working fine thank you :)
