### ISSUE TITLE
interrupt poll failed on some version of linux

### ISSUE THREAD

**Issue by xicilion** [paullouisageneau/libjuice#269]
https://github.com/paullouisageneau/libjuice/blob/master/src/conn_mux.c#L494
```cpp
if (udp_sendto_self(registry_impl->sock, NULL, 0) < 0) {
	if (sockerrno != SEAGAIN && sockerrno != SEWOULDBLOCK) {
		JLOG_WARN("Failed to interrupt poll by triggering socket, errno=%d", sockerrno);
	}
	mutex_unlock(&registry_impl->send_mutex);
	return -1;
}
```

In line 494 of con_mux, the current poll is interrupted to handle the agent using sendto. However, in some versions of Linux, passing NULL to sendto will immediately report an error, causing the interruption to fail. Passing a pointer to a static buffer can solve this problem.

**Comment by paullouisageneau** [comment]
Do you know what C standard library has this behavior? It looks like an over-zealous check as zero-length UDP datagrams are explicitly allowed, and NULL should be a valid pointer for a zero-length buffer. Does https://github.com/paullouisageneau/libjuice/pull/270 fix it?

**Comment by xicilion** [comment]
yes, https://github.com/paullouisageneau/libjuice/pull/270 fixed it.

I found in my testing that the arm64/mips64/riscv64/loong64 architectures of Ubuntu 20.04 all have this issue.
