### ISSUE TITLE
I recommend to add the interface to set the role of agent 

### ISSUE THREAD

**Issue by sinFunc** [paullouisageneau/libjuice#282]
every time, create a connection with ice,there is a warning of role conflict.even though it can fix via negotiation between two pairs.
but if there is a interface to set the role, it would be better. as follow.
void juice_set_mode(juice_agent_t* agent,bool controlling)
{
    agent_set_mode(agent,controlling);
}
void agent_set_mode(juice_agent_t* agent,bool controlling)
{
    agent->mode= controlling ? AGENT_MODE_CONTROLLING : AGENT_MODE_CONTROLLED;
}

**Comment by paullouisageneau** [comment]
I think the ICE role is not something the application should change arbitrarily as RFC 8445 has [specific procedures](https://www.rfc-editor.org/rfc/rfc8445#section-6.1.1) for determining the role.
