### ISSUE TITLE
CMake cannot install juice.h

### ISSUE THREAD

**Issue by Nemirtingas** [paullouisageneau/libjuice#34]
Hi, it looks like in the cmake install rule you've set a wrong path for the include file: include/juice.h instead of include/juice/juice.h.

**Comment by paullouisageneau** [comment]
Oh indeed, thanks!

**Comment by Nemirtingas** [comment]
I'm trying to port your libraries to vcpkg, would you agree ?

**Comment by paullouisageneau** [comment]
Sure, please do!

**Comment by Nemirtingas** [comment]
Ok then. Thanks.
