### ISSUE TITLE
[Question] Can we use something else than Nettle or OpenSSL for HMAC computation ?

### ISSUE THREAD

**Issue by Nemirtingas** [paullouisageneau/libjuice#42]
Hi,
I feel like importing the whole Nettle or OpenSSL lib just for HMAC computation is a bit overkill. Can we use something lighter like https://github.com/kazuho/picohash ?

**Comment by paullouisageneau** [comment]
The rationale for depending for Nettle or OpenSSL was that libdatachannel itself depends either on GnuTLS (so indirectly Nettle) or OpenSSL. That's a good idea to make things easier for people using libjuice by itself.

**Comment by Nemirtingas** [comment]
Yep, I understand, but as libnice is quite hard to build, I think more ppl will use this lib as a substitute. Thats just an idea.

**Comment by Nemirtingas** [comment]
Cool, thanks.
