### ISSUE TITLE
[Windows] Secure random generator

### ISSUE THREAD

**Issue by Nemirtingas** [paullouisageneau/libjuice#44]
vcpkg comment: https://github.com/microsoft/vcpkg/pull/13703#issuecomment-707515118

Missing library for https://github.com/paullouisageneau/libjuice/blob/5d3e8b36fe65b9a856e46f8da397a7ade74b2c44/src/random.c#L49-L62

From the vcpkg auto-build:
```
LNK4075: ignoring '/INCREMENTAL' due to '/OPT:ICF' specification [D:\buildtrees\libjuice\x64-uwp-dbg\juice.vcxproj]
            Creating library D:/buildtrees/libjuice/x64-uwp-dbg/Debug/juice.lib and object D:/buildtrees/libjuice/x64-uwp-dbg/Debug/juice.exp
     4>random.obj : error LNK2019: unresolved external symbol CryptAcquireContext referenced in function random_bytes [D:\buildtrees\libjuice\x64-uwp-dbg\juice.vcxproj]
     4>D:\buildtrees\libjuice\x64-uwp-dbg\Debug\juice.dll : fatal error LNK1120: 1 unresolved externals [D:\buildtrees\libjuice\x64-uwp-dbg\juice.vcxproj]
     4>Done Building Project "D:\buildtrees\libjuice\x64-uwp-dbg\juice.vcxproj" (default targets) -- FAILED.
     3>Done Building Project "D:\buildtrees\libjuice\x64-uwp-dbg\ALL_BUILD.vcxproj" (default targets) -- FAILED.
     1>Done Building Project "D:\buildtrees\libjuice\x64-uwp-dbg\install.vcxproj" (default targets) -- FAILED.
```

Do you want to support WinXP ? If not, you could switch to 
```
#include <bcrypt.h>
#pragma comment(lib, bcrypt)
BCryptGenRandom(NULL, (PUCHAR)buf, (ULONG)size, BCRYPT_USE_SYSTEM_PREFERRED_RNG);
```

The OpenSSL library seems to use it for its random number generator: https://github.com/openssl/openssl/blob/f64f26220442db3c6913188e6014e5bc5bc34653/crypto/rand/rand_win.c#L70

**Comment by paullouisageneau** [comment]
This method actually excludes Windows XP and Windows Vista because the flag `BCRYPT_USE_SYSTEM_PREFERRED_RNG` is not supported on Vista, so the function can't be used like this.

However, the official support for both has ended for some time now so I'll follow your suggestion, I don't see a reason to support them here.

**Comment by Nemirtingas** [comment]
> 
> 
> This method actually excludes Windows XP and Windows Vista because the flag `BCRYPT_USE_SYSTEM_PREFERRED_RNG` is not supported on Vista, so the function can't be used like this.
> 
> However, the official support for both has ended for some time now so I'll follow your suggestion, I don't see a reason to support them here.

Or add the check on the win ver ? Should online add 3 lines of code (#if .. #else ... #endif)

**Comment by paullouisageneau** [comment]
> Or add the check on the win ver ? Should online add 3 lines of code (#if .. #else ... #endif)

A check at compile time is not really useful as it won't be compiled on Windows Vista, only it might be run on it. On Vista it will fail and fallback with a warning, I think it's good enough.

**Comment by Nemirtingas** [comment]
FYI: https://github.com/openssl/openssl/issues/8644#issuecomment-480109330

**Comment by Nemirtingas** [comment]
With that new random generator, I guess libjuice will be supported by vcpkg.

**Comment by paullouisageneau** [comment]
Great, thanks!
