### ISSUE TITLE
Sharing a socket across multiple agents

### ISSUE THREAD

**Issue by stazio** [paullouisageneau/libjuice#46]
Hi Paul,
Would it be possible to make libjuice be able to share a socket across multiple agents? I am specifically looking for the ability to allow an application to allow many peers to connect on the same port.

**Comment by paullouisageneau** [comment]
Even if it's not standard, it might be possible using the ICE credentials to demultiplex the incoming requests. However, I think there is a blocking point with application traffic. ICE doesn't touch it so the only way to differentiate different peers is by their remote address. I think this would prevent from opening multiple peer connections between two peers, since there would be no way left to distinguish the streams (same address and same port).

If you need this for firewall reasons, right now the best you can do is limit the library to a small port range.

**Comment by stazio** [comment]
I don't know much about ICE but if on receive, there is a new source host:port pair can we just iterate through every agent, try and if one of them succeeds in decrypting/decoding it or whatever authentication ICE does, we associate that host:port pair with that agent? Source host:port pairs are always going to be unique. This might also have the effect of allowing ICE sessions to survive even if the peer changes it's IP address (whether it's roaming on an mobile network, switch WiFi networks, etc...).

I might be interested in pursuing this in the near-future if there is a way forward.

**Comment by paullouisageneau** [comment]
> Source host:port pairs are always going to be unique.

Well that's the whole problem: in this case, if the remote is also libjuice, they are not unique anymore. If two peers open two peer connections between them, it'll break.

**Comment by stazio** [comment]
Ohhhh, I forgot about the bi-directional bit of ICE, my use case for ICE is only ever to communicate with a browser. Would it be too difficult to make it a toggleable feature?

**Comment by paullouisageneau** [comment]
In that case it could work! Making it togglable might be tricky but not impossible.

**Comment by stazio** [comment]
I wouldn't be opposed to making it be a compile-time thing.

**Comment by stazio** [comment]
How much work would it be to add support for this? I might be inclined to try to do this if it isn't too difficult.

**Comment by paullouisageneau** [comment]
It would require some work. I think the simpler way to achieve it would be to introduce a thread listening on a unique socket, with a map of ICE credentials to do the demultiplexing. Agent threads would register their input function in the map of ICE credentials. Agent threads would also need substantial to change their synchronization from select() to a condition variable.

**Comment by paullouisageneau** [comment]
> This might also have the effect of allowing ICE sessions to survive even if the peer changes it's IP address (whether it's roaming on an mobile network, switch WiFi networks, etc...).

Thinking about it, I don't think it will work on browsers. Proper ICE agents bind on particular interfaces and requires renegotiation if the host changes addresses.

**Comment by paullouisageneau** [comment]
This is implemented as an option by https://github.com/paullouisageneau/libjuice/pull/148 (duplicate issue https://github.com/paullouisageneau/libjuice/issues/144)
