### ISSUE TITLE
undefined reference to `getrandom'

### ISSUE THREAD

**Issue by Remainfox** [paullouisageneau/libjuice#54]
compile error as follow:  

gcc -pthread -o tests test/connectivity.o test/crc32.o test/main.o test/notrickle.o test/server.o test/stun.o    libjuice.a
libjuice.a(random.o): In function `juice_random':
random.c:(.text+0x21): undefined reference to `getrandom'
collect2: error: ld returned 1 exit status

ubuntu 16.04
Linux ubuntu 4.4.0-189-generic #219-Ubuntu SMP Tue Aug 11 12:26:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by paullouisageneau** [comment]
It seems Ubuntu 16.04 only has glibc 2.23 whereas getrandom was introduced in 2.25. Since 16.04 is still supported for a few months I'll push a fix to detect it and fall back.
