### ISSUE TITLE
have question with udp_get_addrs 

### ISSUE THREAD

**Issue by Remainfox** [paullouisageneau/libjuice#64]
if ((sa->sa_family == AF_INET || sa->sa_family == AF_INET6) && !addr_is_local(sa) &&
    !(has_temp_inet6 && sa->sa_family == AF_INET6 && !addr_is_temp_inet6(sa))) {

!(has_temp_inet6 && sa->sa_family == AF_INET6 && !addr_is_temp_inet6(sa)))  
The first "!" does not need to be added, this means that non-temporary ipv6 addresses can be added

**Comment by paullouisageneau** [comment]
The logic here is actually that as soon as a temporary address is found, non-temporary addresses must not be listed, as commented here: https://github.com/paullouisageneau/libjuice/blob/421c650d9dd85c4824410f09274d95ce64b6e2e3/src/udp.c#L276

**Comment by Remainfox** [comment]
oh, i see , thanks
