### ISSUE TITLE
Got STUN error code 438, reason "Stale nonce"

### ISSUE THREAD

**Issue by yyq2016** [paullouisageneau/libjuice#90]
I got the error after run the libjuice after 20 minute,
cloud u pls resolve it?
by the way, i use mqtt_c (for signaling client)/mosquitto(for signaling server).
thanks!

**Comment by paullouisageneau** [comment]
The 438 Stale nonce temporary error is expected to happen at some point when using a TURN server. It means the server decided the former nonce has outlived its validity time and the client must retry with the new nonce given in the error. Does the error causes an issue with the ICE session?

**Comment by yyq2016** [comment]
yes, I try to run libjuice as a whole example of ICE.

**Comment by paullouisageneau** [comment]
I'm closing this, the 438 temporary error is expected, please reopen if something is broken.
