### ISSUE TITLE
0.7.3 has warnings when built with NO_SERVER

### ISSUE THREAD

**Issue by glynj-bsquare** [paullouisageneau/libjuice#95]
Probably not serious, but thought this would be useful to know.

Toolchain is attached. 
[toolchain.txt](https://github.com/paullouisageneau/libjuice/files/6506744/toolchain.txt)

Running on Ubuntu 16.04.

mkdir build 
cd build
cmake  -DNO_SERVER=1 ..
make

-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/datav/DataV/tool-chains/external-libraries/build.x86_64/libjuice-0.7.3/build
Scanning dependencies of target juice
[  3%] Building C object CMakeFiles/juice.dir/src/addr.c.o
[  7%] Building C object CMakeFiles/juice.dir/src/agent.c.o
[ 10%] Building C object CMakeFiles/juice.dir/src/crc32.c.o
[ 14%] Building C object CMakeFiles/juice.dir/src/const_time.c.o
[ 17%] Building C object CMakeFiles/juice.dir/src/base64.c.o
[ 21%] Building C object CMakeFiles/juice.dir/src/hash.c.o
[ 25%] Building C object CMakeFiles/juice.dir/src/hmac.c.o
[ 28%] Building C object CMakeFiles/juice.dir/src/ice.c.o
[ 32%] Building C object CMakeFiles/juice.dir/src/juice.c.o
/home/tool-chains/external-libraries/build.x86_64/libjuice-0.7.3/src/juice.c: In function ‘juice_server_create’:
/home/
tool-chains/external-libraries/build.x86_64/libjuice-0.7.3/src/juice.c:170:79: warning: unused parameter ‘config’ [-Wunused-parameter]
 PORT juice_server_t *juice_server_create(const juice_server_config_t *config) {
                                                                       ^
/home/tool-chains/external-libraries/build.x86_64/libjuice-0.7.3/src/juice.c: In function ‘juice_server_destroy’:
/home/tool-chains/external-libraries/build.x86_64/libjuice-0.7.3/src/juice.c:181:56: warning: unused parameter ‘server’ [-Wunused-parameter]
 JUICE_EXPORT void juice_server_destroy(juice_server_t *server) {
                                                        ^
/home/tool-chains/external-libraries/build.x86_64/libjuice-0.7.3/src/juice.c: In function ‘juice_server_get_port’:
/home/tool-chains/external-libraries/build.x86_64/libjuice-0.7.3/src/juice.c:188:61: warning: unused parameter ‘server’ [-Wunused-parameter]
 JUICE_EXPORT uint16_t juice_server_get_port(juice_server_t *server) {
                                                             ^
/home/tool-chains/external-libraries/build.x86_64/libjuice-0.7.3/src/juice.c: In function ‘juice_server_create’:
/home/tool-chains/external-libraries/build.x86_64/libjuice-0.7.3/src/juice.c:179:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
[ 35%] Building C object CMakeFiles/juice.dir/src/log.c.o
[ 39%] Building C object CMakeFiles/juice.dir/src/random.c.o
[ 42%] Building C object CMakeFiles/juice.dir/src/server.c.o
[ 46%] Building C object CMakeFiles/juice.dir/src/stun.c.o
[ 50%] Building C object CMakeFiles/juice.dir/src/timestamp.c.o
[ 53%] Building C object CMakeFiles/juice.dir/src/turn.c.o
[ 57%] Building C object CMakeFiles/juice.dir/src/udp.c.o
[ 60%] Linking C shared library libjuice.so
[ 60%] Built target juice
Scanning dependencies of target juice-tests
[ 64%] Building C object CMakeFiles/juice-tests.dir/test/main.c.o
[ 67%] Building C object CMakeFiles/juice-tests.dir/test/crc32.c.o
[ 71%] Building C object CMakeFiles/juice-tests.dir/test/base64.c.o
[ 75%] Building C object CMakeFiles/juice-tests.dir/test/stun.c.o
[ 78%] Building C object CMakeFiles/juice-tests.dir/test/gathering.c.o
[ 82%] Building C object CMakeFiles/juice-tests.dir/test/connectivity.c.o
[ 85%] Building C object CMakeFiles/juice-tests.dir/test/notrickle.c.o
[ 89%] Building C object CMakeFiles/juice-tests.dir/test/turn.c.o
[ 92%] Building C object CMakeFiles/juice-tests.dir/test/server.c.o
[ 96%] Building C object CMakeFiles/juice-tests.dir/test/conflict.c.o
[100%] Linking C executable tests
[100%] Built target juice-tests
[ 60%] Built target juice
[100%] Built target juice-tests

**Comment by paullouisageneau** [comment]
Thanks for reporting, this should be fixed in https://github.com/paullouisageneau/libjuice/pull/96
