### ISSUE TITLE
Does " connectivity.c " test work only in local network ??

### ISSUE THREAD

**Issue by norayrsoftware** [paullouisageneau/libjuice#97]
I want to create simple P2P. I create a STUN/TURN server using violet library.
And now i want to divide the connectivity test into 2 clients and to make a simple P2P.
But i get confused if i can make P2P when clients behind different NATs.

**Comment by paullouisageneau** [comment]
>  But i get confused if i can make P2P when clients behind different NATs.

Yes you can, that's the point of ICE. If at least one of the two NATs is not problematic (most residential gateway are OK), it will open a direct connection with STUN, otherwise, it will need to relay the connection via a TURN server.

**Comment by norayrsoftware** [comment]
Thanks !
